### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by Omij** [LegendaryAK/Rock-Paper-Scissors#1]
I compiled your code into an applet but when I attempt to run it I'm getting a "RuntimeException" error from the Java console. The error description says "java.lang.reflect.InvocationTargetException". Any ideas?

**Comment by LegendaryAK** [comment]
Yeah pretty sure I need to change the first snippet of code, where I have the import.java.util part. I need to have it import Applet stuff, I just don't know how yet..

**Comment by Omij** [comment]
Fix it!

**Comment by Omij** [comment]
I give up trying to make this an applet. It was just an experiment anyway.
